name: CI/CD Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dockerfile
        run: docker build . --file product-service/Dockerfile --tag rubyshores/prac7:latest

      - name: Push to dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to DockerHub
        run: docker push rubyshores/prac7:latest
        #dckr_pat_8EgXsagCmFAZ__1gTCm1JIqQ2w4
