name: CD Yandex
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-and-push-yc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Yandex
      run: docker build . --file refund-service/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/refund-service:latest
    - name: Login to YC Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}
    - name: push to YC Registry
      run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/refund-service:latest

