name: Build and Push Product Service

on:
  push:
    branches: [ main ]
    paths:
      - 'product-service/app/api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'product-service/app/api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push product-service image
      uses: docker/build-push-action@v2
      with:
        context: ./product-service
        file: ./product-service/Dockerfile
        push: true
        tags: rubyshores/prac7:latest

    - name: Logout from DockerHub
      run: docker logout
